# Generated by Django 5.0.1 on 2026-03-01 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ecf_data', serialize=False, to='api.venta')),
                ('track_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ecf_tipo', models.CharField(default='31', max_length=3)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('xml_firmado', models.TextField(blank=True, help_text='XML completo firmado (XMLDSig)')),
                ('respuesta_dgii', models.JSONField(blank=True, help_text='Respuesta cruda de la DGII', null=True)),
                ('qr_code_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='certificado_digital',
        ),
        migrations.AddField(
            model_name='negocio',
            name='certificado_digital_path',
            field=models.CharField(blank=True, help_text='Ruta segura al .p12', max_length=255),
        ),
        migrations.AddField(
            model_name='negocio',
            name='certificado_pass_env',
            field=models.CharField(blank=True, help_text='Nombre de ENV VAR con la clave', max_length=100),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.periodocontable'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='codigo_seguridad_dgii',
            field=models.CharField(blank=True, help_text='Código de 6 dígitos del e-CF', max_length=6),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_fiscal',
            field=models.CharField(choices=[('NO_FISCAL', 'No Fiscal'), ('PENDIENTE', 'Pendiente de Envío'), ('ENVIADO', 'Enviado a DGII'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('EN_CONTINGENCIA', 'En Contingencia')], default='NO_FISCAL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['negocio', 'fecha'], name='api_asiento_negocio_3033d3_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['negocio', 'estado'], name='api_asiento_negocio_2bf860_idx'),
        ),
        migrations.AddConstraint(
            model_name='lineaasiento',
            constraint=models.CheckConstraint(check=models.Q(('debe__gte', 0), ('haber__gte', 0)), name='monto_positivo'),
        ),
    ]
