# Generated by Django 5.0.1 on 2026-03-02 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_facturaelectronica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque/Transferencia'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('CREDITO', 'A Crédito')], default='CREDITO', max_length=15),
        ),
        migrations.AddField(
            model_name='compra',
            name='itbis_retenido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='retencion_renta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_bienes_servicios',
            field=models.CharField(choices=[('01', '01 - Gastos de Personal'), ('02', '02 - Gastos por Trabajos, Suministros y Servicios'), ('03', '03 - Arrendamientos'), ('04', '04 - Gastos de Activos Fijos'), ('05', '05 - Gastos de Representación'), ('06', '06 - Otras Deducciones Admitidas'), ('07', '07 - Gastos Financieros'), ('08', '08 - Gastos Extraordinarios'), ('09', '09 - Compras y Gastos que forman parte del Costo de Venta'), ('10', '10 - Adquisiciones de Activos'), ('11', '11 - Gastos de Seguros'), ('12', '12 - Otros Gastos'), ('13', '13 - Compra de bienes')], default='02', max_length=2),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_retencion',
            field=models.CharField(blank=True, help_text='Según norma 07-2007', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='venta_referencia',
            field=models.ForeignKey(blank=True, help_text='Venta original referenciada por nota de crédito/débito', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_debito', to='api.venta'),
        ),
        migrations.CreateModel(
            name='Conciliacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('saldo_extracto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo_libros', models.DecimalField(decimal_places=2, max_digits=15)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('COMPLETADA', 'Completada')], default='BORRADOR', max_length=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='api.cuentabancaria')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=7)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('conciliado', models.BooleanField(default=False)),
                ('importado_de', models.CharField(blank=True, help_text='Fuente del extracto', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='api.cuentabancaria')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
                'indexes': [models.Index(fields=['cuenta', 'fecha'], name='api_movimie_cuenta__203b0b_idx'), models.Index(fields=['cuenta', 'conciliado'], name='api_movimie_cuenta__122446_idx')],
            },
        ),
    ]
