# Generated by Django 5.0.1 on 2026-03-13 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cotizacion_cuentaporcobrar_cuentaporpagar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSeguridad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('LOGIN_FALLIDO', 'Intentos de login fallidos'), ('CAMBIO_ROL', 'Cambio de rol administrativo'), ('ELIMINACION_MASIVA', 'Eliminacion masiva de datos'), ('ACCESO_FUERA_HORARIO', 'Acceso fuera de horario'), ('IP_NUEVA', 'Login desde IP nueva'), ('DESCUADRE', 'Descuadre de caja significativo'), ('ANULACIONES', 'Exceso de anulaciones'), ('DESCUENTO_EXCESIVO', 'Descuento excesivo aplicado'), ('TRANSACCION_ALTA', 'Transaccion de monto alto'), ('ANOMALIA', 'Anomalia detectada'), ('CUENTA_BLOQUEADA', 'Cuenta bloqueada'), ('IP_BLOQUEADA', 'IP bloqueada')], max_length=30)),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Critica')], default='MEDIA', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('leida', models.BooleanField(default=False)),
                ('resuelta', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('key_hash', models.CharField(max_length=255, unique=True)),
                ('key_prefix', models.CharField(max_length=12)),
                ('scopes', models.JSONField(default=list, help_text="Ej: ['ventas:read', 'productos:read']")),
                ('activa', models.BooleanField(default=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='BackupRegistro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('DIARIO', 'Diario'), ('MIGRACION', 'Pre-migracion'), ('MANUAL', 'Manual')], max_length=15)),
                ('archivo', models.CharField(max_length=500)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('encriptado', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('VERIFICADO', 'Verificado')], default='EN_PROGRESO', max_length=15)),
                ('test_restauracion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmacionTransaccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('objeto_id', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=20)),
                ('expira_en', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='IPBloqueada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('razon', models.CharField(max_length=255)),
                ('intentos', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('permanente', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'IPs Bloqueadas',
            },
        ),
        migrations.CreateModel(
            name='LicenciaSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave_licencia', models.CharField(max_length=512, unique=True)),
                ('tipo', models.CharField(choices=[('TRIAL', 'Prueba'), ('BASICO', 'Basico'), ('PROFESIONAL', 'Profesional'), ('ENTERPRISE', 'Enterprise')], max_length=20)),
                ('max_usuarios', models.IntegerField(default=5)),
                ('max_sucursales', models.IntegerField(default=1)),
                ('modulos', models.JSONField(default=list)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('firma_hmac', models.CharField(max_length=128)),
                ('ultima_verificacion', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SesionActiva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='TokenPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('ultimos_4', models.CharField(max_length=4)),
                ('tipo_tarjeta', models.CharField(max_length=20)),
                ('expiracion_mes', models.IntegerField()),
                ('expiracion_ano', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='duracion_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resultado',
            field=models.CharField(choices=[('SUCCESS', 'Exitoso'), ('FAILED', 'Fallido')], default='SUCCESS', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='sesion_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='consentimiento_datos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_consentimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='horario_acceso_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='horario_acceso_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='paises_permitidos',
            field=models.JSONField(blank=True, default=list, help_text='ISO 3166-1 alfa-2 codes permitidos para acceso (vacio = sin restriccion)'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='umbral_confirmacion',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Monto a partir del cual se requiere doble confirmacion', max_digits=12),
        ),
        migrations.AddField(
            model_name='usuario',
            name='horario_acceso_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='horario_acceso_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ips_conocidas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usuario',
            name='max_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override del limite de descuento por rol', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('LOGIN', 'Inicio de Sesion'), ('LOGOUT', 'Cierre de Sesion'), ('LOGIN_FALLIDO', 'Intento Fallido'), ('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver'), ('EXPORT', 'Exportar'), ('PRINT', 'Imprimir'), ('MFA_SETUP', 'Configuracion MFA'), ('MFA_VERIFY', 'Verificacion MFA'), ('PASSWORD_CHANGE', 'Cambio de Password'), ('ROLE_CHANGE', 'Cambio de Rol'), ('PERMISSION_CHANGE', 'Cambio de Permisos'), ('SESSION_INVALIDATE', 'Invalidacion de Sesion'), ('API_KEY_CREATE', 'Creacion de API Key'), ('SENSITIVE_ACCESS', 'Acceso a Datos Sensibles')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrador'), ('ADMIN_NEGOCIO', 'Administrador del Negocio'), ('GERENTE', 'Gerente'), ('CONTADOR', 'Contador'), ('CAJERO', 'Cajero'), ('VENDEDOR', 'Vendedor'), ('ALMACEN', 'Encargado de Almacen'), ('AUDITOR', 'Auditor'), ('INVENTARIO', 'Encargado de Inventario')], default='CAJERO', max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resultado'], name='api_auditlo_resulta_7c3aea_idx'),
        ),
        migrations.AddField(
            model_name='alertaseguridad',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_seguridad', to='api.negocio'),
        ),
        migrations.AddField(
            model_name='alertaseguridad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apikey',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apikey',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='api.negocio'),
        ),
        migrations.AddField(
            model_name='confirmaciontransaccion',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmaciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confirmaciontransaccion',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.negocio'),
        ),
        migrations.AddField(
            model_name='confirmaciontransaccion',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenciasistema',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='api.negocio'),
        ),
        migrations.AddField(
            model_name='sesionactiva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokenpago',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_pago', to='api.cliente'),
        ),
        migrations.AddField(
            model_name='tokenpago',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.negocio'),
        ),
        migrations.AddIndex(
            model_name='alertaseguridad',
            index=models.Index(fields=['negocio', 'tipo', 'creado_en'], name='api_alertas_negocio_904882_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaseguridad',
            index=models.Index(fields=['leida', 'resuelta'], name='api_alertas_leida_b21a61_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionactiva',
            index=models.Index(fields=['usuario', 'activa'], name='api_sesiona_usuario_a74032_idx'),
        ),
    ]
