# Generated by Django 5.0.1 on 2026-03-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alertaseguridad_apikey_backupregistro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='Hashed backup codes for 2FA recovery'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
