# Generated by Django 5.0.1 on 2026-03-13 19:17

from django.db import migrations


def encrypt_plaintext_secrets(apps, schema_editor):
    """Encrypt any existing plaintext TOTP secrets using AES-256-GCM."""
    import os
    key_hex = os.getenv('AES_256_KEY', '')
    if not key_hex:
        # No encryption key configured; skip (dev environment)
        return

    Usuario = apps.get_model('api', 'Usuario')
    users_with_secret = Usuario.objects.exclude(two_factor_secret='').exclude(two_factor_secret__contains=':')
    count = 0
    for user in users_with_secret:
        try:
            from api.security.data_protection import encrypt_aes256
            user.two_factor_secret = encrypt_aes256(user.two_factor_secret)
            user.save(update_fields=['two_factor_secret'])
            count += 1
        except Exception:
            pass  # Skip if encryption fails
    if count:
        print(f'\n  Encrypted {count} plaintext TOTP secret(s).')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usuario_backup_codes_alter_usuario_two_factor_secret'),
    ]

    operations = [
        migrations.RunPython(encrypt_plaintext_secrets, noop),
    ]
