# Generated by Django 5.0.1 on 2026-03-14 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_encrypt_existing_totp_secrets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10)),
                ('tasa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.CharField(choices=[('GENERAL', 'Impuesto General'), ('REDUCIDO', 'Tasa Reducida'), ('EXENTO', 'Exento'), ('ESPECIAL', 'Impuesto Especial')], default='GENERAL', max_length=20)),
                ('aplica_a', models.CharField(choices=[('PRODUCTOS', 'Productos'), ('SERVICIOS', 'Servicios'), ('AMBOS', 'Productos y Servicios')], default='AMBOS', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='api.pais')),
            ],
            options={
                'ordering': ['pais', 'nombre'],
                'unique_together': {('pais', 'codigo')},
            },
        ),
    ]
