# Generated by Django 5.0.1 on 2026-03-15 15:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_impuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_adquisicion', models.DateField()),
                ('fecha_inicio_depreciacion', models.DateField()),
                ('costo_adquisicion', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_residual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vida_util_meses', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('metodo_depreciacion', models.CharField(choices=[('LINEAL', 'Línea Recta'), ('SALDO_DECRECIENTE', 'Saldo Decreciente'), ('UNIDADES_PRODUCCION', 'Unidades de Producción'), ('SUM_DIGITOS', 'Suma de Dígitos')], default='LINEAL', max_length=25)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DEPRECIADO_TOTAL', 'Depreciado Totalmente'), ('DADO_DE_BAJA', 'Dado de Baja'), ('EN_MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', max_length=20)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='activos_fijos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cuenta_contable', models.ForeignKey(help_text='Cuenta de activo fijo', on_delete=django.db.models.deletion.PROTECT, related_name='activos_fijos', to='api.cuentacontable')),
                ('cuenta_depreciacion', models.ForeignKey(help_text='Cuenta de depreciación acumulada', on_delete=django.db.models.deletion.PROTECT, related_name='activos_depreciacion', to='api.cuentacontable')),
                ('cuenta_gasto', models.ForeignKey(help_text='Cuenta de gasto por depreciación', on_delete=django.db.models.deletion.PROTECT, related_name='activos_gasto_dep', to='api.cuentacontable')),
                ('factura_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_fijos', to='api.compra')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos_fijos', to='api.negocio')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_vendidos', to='api.proveedor')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_asignados', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_fijos', to='api.sucursal')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='BajaActivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_baja', models.DateField()),
                ('motivo', models.CharField(choices=[('VENTA', 'Venta'), ('DETERIORO', 'Deterioro'), ('ROBO', 'Robo'), ('OBSOLESCENCIA', 'Obsolescencia'), ('DONACION', 'Donación')], max_length=20)),
                ('valor_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ganancia_perdida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baja', to='api.activofijo')),
                ('asiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_activo', to='api.asientocontable')),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas_autorizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_baja'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaActivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('vida_util_default', models.IntegerField(help_text='Vida útil en meses')),
                ('metodo_default', models.CharField(choices=[('LINEAL', 'Línea Recta'), ('SALDO_DECRECIENTE', 'Saldo Decreciente'), ('UNIDADES_PRODUCCION', 'Unidades de Producción'), ('SUM_DIGITOS', 'Suma de Dígitos')], default='LINEAL', max_length=25)),
                ('cuenta_activo_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_activo_fijo', to='api.cuentacontable')),
                ('cuenta_depreciacion_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_depreciacion_acum', to='api.cuentacontable')),
                ('cuenta_gasto_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_gasto_depreciacion', to='api.cuentacontable')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_activo', to='api.negocio')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('negocio', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='activofijo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='api.categoriaactivo'),
        ),
        migrations.CreateModel(
            name='DepreciacionMensual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto_depreciacion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depreciacion_acumulada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_en_libros', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciaciones', to='api.activofijo')),
                ('asiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciaciones', to='api.asientocontable')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciaciones', to='api.periodocontable')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='activofijo',
            index=models.Index(fields=['negocio', 'estado'], name='api_activof_negocio_77b2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='activofijo',
            index=models.Index(fields=['negocio', 'categoria'], name='api_activof_negocio_7b245e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activofijo',
            unique_together={('negocio', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='depreciacionmensual',
            unique_together={('activo', 'periodo')},
        ),
    ]
