# Generated by Django 5.0.1 on 2026-03-15 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_activos_fijos'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientocontable',
            name='tipo',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('VENTA', 'Venta'), ('COMPRA', 'Compra'), ('PAGO', 'Pago'), ('COBRO', 'Cobro'), ('AJUSTE', 'Ajuste'), ('CIERRE', 'Cierre'), ('AUTOMATICO', 'Automático')], default='MANUAL', max_length=15),
        ),
        migrations.CreateModel(
            name='ArchivoImportacionBancaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('formato', models.CharField(choices=[('OFX', 'OFX/QFX'), ('MT940', 'MT940/SWIFT'), ('CSV_BANCO', 'CSV Banco'), ('QIF', 'QIF')], max_length=10)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('registros_importados', models.IntegerField(default=0)),
                ('registros_conciliados', models.IntegerField(default=0)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to='api.cuentabancaria')),
                ('importado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones_bancarias', to='api.negocio')),
            ],
            options={
                'ordering': ['-fecha_importacion'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_APROBACION', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=25)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_creados', to=settings.AUTH_USER_MODEL)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='api.departamento')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='api.negocio')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='api.periodocontable')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('entidad', models.CharField(choices=[('ORDEN_COMPRA', 'Orden de Compra'), ('COMPRA', 'Compra'), ('GASTO', 'Gasto'), ('DESCUENTO', 'Descuento'), ('BAJA_ACTIVO', 'Baja de Activo'), ('AJUSTE_INVENTARIO', 'Ajuste de Inventario'), ('NOTA_CREDITO', 'Nota de Crédito'), ('PRESUPUESTO', 'Presupuesto')], max_length=25)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='api.negocio')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('negocio', 'entidad')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('rol_aprobador', models.CharField(choices=[('GERENTE', 'Gerente'), ('ADMIN_NEGOCIO', 'Admin Negocio'), ('CONTADOR', 'Contador')], max_length=20)),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('auto_aprobar_bajo_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('timeout_horas', models.IntegerField(default=48)),
                ('notificar_por', models.CharField(choices=[('EMAIL', 'Email'), ('WEBSOCKET', 'WebSocket'), ('AMBOS', 'Ambos')], default='WEBSOCKET', max_length=10)),
                ('usuario_especifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasos_workflow_asignados', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='api.workflowconfig')),
            ],
            options={
                'ordering': ['workflow', 'orden'],
                'unique_together': {('workflow', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudAprobacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada'), ('ESCALADA', 'Escalada')], default='PENDIENTE', max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='api.workflowconfig')),
                ('paso_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_en_paso', to='api.workflowstep')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DecisionAprobacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], max_length=10)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_decision', models.DateTimeField(auto_now_add=True)),
                ('aprobador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones_tomadas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='api.solicitudaprobacion')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='api.workflowstep')),
            ],
            options={
                'ordering': ['fecha_decision'],
            },
        ),
        migrations.CreateModel(
            name='LineaPresupuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mes_01', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes_02', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes_03', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes_04', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes_05', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes_06', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes_07', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes_08', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes_09', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes_10', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes_11', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mes_12', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_anual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_presupuesto', to='api.cuentacontable')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='api.presupuesto')),
            ],
            options={
                'ordering': ['cuenta_contable__codigo'],
                'unique_together': {('presupuesto', 'cuenta_contable')},
            },
        ),
        migrations.CreateModel(
            name='TransaccionBancaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONCILIADA', 'Conciliada'), ('EXCLUIDA', 'Excluida')], default='PENDIENTE', max_length=12)),
                ('confianza_match', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('fecha_conciliacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conciliada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_importadas', to='api.cuentabancaria')),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='api.archivoimportacionbancaria')),
                ('movimiento_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_match', to='api.movimientobancario')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_bancarias', to='api.negocio')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['cuenta_bancaria', 'estado'], name='api_transac_cuenta__27c6bb_idx'), models.Index(fields=['cuenta_bancaria', 'fecha'], name='api_transac_cuenta__acc2d5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudaprobacion',
            index=models.Index(fields=['content_type', 'object_id'], name='api_solicit_content_12fb1f_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudaprobacion',
            index=models.Index(fields=['estado'], name='api_solicit_estado_ae82bc_idx'),
        ),
    ]
